---
title: Hackmurerie

exclude: ['/scripts', '/Gemfile', '/Makefile', '/README.md']

permalink: pretty

collections:
  hackmurerie:
    output: true

defaults:
  - scope:
      path: '_wadcoms'
    values:
      layout: bin
