---
SMB:
  label: SMB
  description: Vous avez trouvé le service SMB ouvert et vous voulez savoir ce que vous pouvez faire avec.

WMI:
  label: WMI
  description: Le service Windows Management Intstrumentation (WMI) est ouvert et vous devez savoir ce que vous pouvez faire avec.

DCOM:
  label: DCOM
  description: Le service DCOM est ouvert et vous devez savoir ce que vous pouvez faire avec.

Kerberos:
  label: Kerberos
  description: Vous avez trouvé le service kerberos ouvert et vous devez savoir ce que vous pouvez faire avec.

RPC:
  label: RPC
  description: Vous avez trouvé le service RPC ouvert et vous devez savoir ce que vous pouvez en faire.

LDAP:
  label: LDAP
  description: Le service LDAP est ouvert et vous devez savoir ce que vous pouvez en faire.

SSH:
  label: SSH
  description: Vous avez trouvé le service SSH ouvert et vous voulez savoir ce que vous pouvez faire avec.
  
NTLM:
  label: NTLM
  description: La commande concerne le protocole NTLM.

DNS:
  label: DNS
  description: La commande concerne le service DNS.

AV:
  label: Antivirus
  description: La commande/payload concerne le contournement de l'AV/AMSI.

ADCS:
  label: ADCS
  description: La commande/charge de travail concerne les services de certification Active Directory.

Web:
  label: Web
  description: Les commandes/charges utiles concernent les serveurs web.

Approved:
  label: Approved
  description: L'outil est approuvé.

Testing:
  label: Testing
  description: L'outil est en phase de test.

New:
  label-tool: New
  description: L'outil est tout nouveau.