---
SMB:
  label: SMB
  description: Vous avez trouvé le service SMB ouvert et vous voulez savoir ce que vous pouvez faire avec.

WMI:
  label: WMI
  description: Le service Windows Management Intstrumentation (WMI) est ouvert et vous devez savoir ce que vous pouvez faire avec.

DCOM:
  label: DCOM
  description: Le service DCOM est ouvert et vous devez savoir ce que vous pouvez faire avec.

Kerberos:
  label: Kerberos
  description: Vous avez trouvé le service kerberos ouvert et vous devez savoir ce que vous pouvez faire avec.

RPC:
  label: RPC
  description: Vous avez trouvé le service RPC ouvert et vous devez savoir ce que vous pouvez en faire.

LDAP:
  label: LDAP
  description: Le service LDAP est ouvert et vous devez savoir ce que vous pouvez en faire.

NTLM:
  label: NTLM
  description: La commande concerne le protocole NTLM.

DNS:
  label: DNS
  description: La commande concerne le service DNS.

HTTP:
  label: HTTP
  description: La commande concerne le service HTTP.
